[profile.default]
solc = "0.8.28"
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

